#!/usr/bin/env python3
"""
IDS-ML v2.0 -- Emergency Port & Config Fix
Run this when the dashboard is blank or shows wrong port.
Usage: python fix_now.py
"""
import os, re, socket, subprocess, sys, time, urllib.request, shutil

BASE     = os.path.dirname(os.path.abspath(__file__))
FRONTEND = os.path.join(BASE, "frontend")

def is_port_open(port, host="127.0.0.1", timeout=1.0):
    try:
        s = socket.create_connection((host, port), timeout=timeout)
        s.close(); return True
    except: return False

def http_get(url, timeout=3):
    try:
        with urllib.request.urlopen(url, timeout=timeout) as r:
            return r.status, r.read().decode()
    except urllib.error.HTTPError as e:
        return e.code, e.read().decode()
    except Exception as ex:
        return None, str(ex)

def kill_port(port):
    try:
        result = subprocess.run(["netstat", "-ano"], capture_output=True, text=True)
        for line in result.stdout.splitlines():
            if f":{port} " in line and ("LISTENING" in line or "ESTABLISHED" in line):
                parts = line.strip().split()
                pid = parts[-1]
                if pid.isdigit() and pid != "0":
                    subprocess.run(["taskkill", "/F", "/PID", pid], capture_output=True)
                    print(f"  Killed PID {pid} on port {port}")
                    return True
    except Exception as e:
        print(f"  Could not kill port {port}: {e}")
    return False

def what_is_on_port(port):
    try:
        result = subprocess.run(["netstat", "-ano"], capture_output=True, text=True)
        pids = set()
        for line in result.stdout.splitlines():
            if f":{port} " in line and "LISTENING" in line:
                parts = line.strip().split()
                pids.add(parts[-1])
        for pid in pids:
            r2 = subprocess.run(
                ["tasklist", "/FI", f"PID eq {pid}", "/FO", "CSV"],
                capture_output=True, text=True
            )
            for l in r2.stdout.splitlines():
                if pid in l:
                    return f"PID {pid} -> {l.split(',')[0].strip(chr(34))}"
    except: pass
    return "unknown"

print("=" * 60)
print("  IDS-ML v2.0 -- Emergency Fix")
print("=" * 60)

# Step 1: Identify what's on port 8000
print("\n[1] Checking port 8000...")
if is_port_open(8000):
    proc = what_is_on_port(8000)
    print(f"  WARNING: Port 8000 occupied by: {proc}")
    status, body = http_get("http://localhost:8000/health")
    if status == 200 and "IDS-ML" in body:
        print(f"  It IS an IDS-ML backend (health OK) -- killing it so start.py reclaims 8000")
        kill_port(8000)
        time.sleep(2)
        if not is_port_open(8000):
            print(f"  OK: Port 8000 now free!")
        else:
            print(f"  WARNING: Port 8000 still busy -- may need manual kill via Task Manager")
    else:
        print(f"  Not an IDS-ML backend (health={status}) -- will leave it, start.py uses fallback")
else:
    print("  OK: Port 8000 is free")

# Step 2: Find the actual running IDS-ML backend
print("\n[2] Scanning for live IDS-ML backend...")
backend_port = None
check_ports = [8000, 8001, 8002, 8003, 8080, 8090, 9000, 9001, 9002]

for p in check_ports:
    if is_port_open(p):
        st, body = http_get(f"http://localhost:{p}/health")
        if st == 200 and "IDS-ML" in body:
            backend_port = p
            print(f"  FOUND: IDS-ML backend on port {backend_port}")
            break
        else:
            print(f"  Port {p} open but not IDS-ML (status={st})")

if not backend_port:
    print("  ERROR: No IDS-ML backend found running!")
    print("\n  --> Run: python start.py")
    print("  --> Then re-run: python fix_now.py")
    sys.exit(1)

# Step 3: Update config.js to correct port
print(f"\n[3] Updating config.js -> port {backend_port}...")
ver = str(int(time.time()))
cfg_path = os.path.join(FRONTEND, "js", "config.js")
cfg_content = (
    "// Auto-generated by fix_now.py / start.py -- do NOT edit manually\n"
    f'const API_BASE = "http://localhost:{backend_port}";\n'
)
with open(cfg_path, "w", encoding="utf-8") as f:
    f.write(cfg_content)
print(f"  OK: config.js -> API_BASE = http://localhost:{backend_port}")

# Step 4: Update HTML cache-buster timestamps
print(f"\n[4] Busting browser cache (v={ver})...")
for html_name in ["index.html", "dashboard.html", "register.html"]:
    hp = os.path.join(FRONTEND, html_name)
    if not os.path.exists(hp): continue
    hc = open(hp, encoding="utf-8", errors="replace").read()
    hc_new = re.sub(r'config\.js(\?v=[\w]*)?', f'config.js?v={ver}', hc)
    if hc_new != hc:
        with open(hp, "w", encoding="utf-8") as hf:
            hf.write(hc_new)
        print(f"  OK: {html_name} cache-busted")
    else:
        print(f"  INFO: {html_name} -- no config.js reference found to update")

# Step 5: Check frontend server
print(f"\n[5] Checking frontend server on port 3000...")
if is_port_open(3000):
    print("  OK: Frontend server running on port 3000")
else:
    print("  ERROR: Frontend server on port 3000 is DOWN!")
    fe_server = os.path.join(BASE, "frontend_server.py")
    if os.path.exists(fe_server):
        print("  Attempting to start frontend_server.py...")
        kwargs = {}
        if sys.platform == "win32":
            kwargs["creationflags"] = subprocess.CREATE_NEW_CONSOLE
        subprocess.Popen([sys.executable, fe_server], cwd=BASE, **kwargs)
        time.sleep(2)
        if is_port_open(3000):
            print("  OK: Frontend server started on port 3000")
        else:
            print("  WARNING: Frontend server did not start automatically")
            print("  --> Run: python start.py  (starts both backend + frontend)")
    else:
        print("  --> Run: python start.py  (starts both servers)")

# Step 6: Final status
print(f"\n{'='*60}")
print("  FINAL STATUS")
print(f"{'='*60}")
st, _ = http_get(f"http://localhost:{backend_port}/health")
fe_up  = is_port_open(3000)
print(f"  Backend  http://localhost:{backend_port}/health  ->  HTTP {st}")
print(f"  Frontend http://127.0.0.1:3000               ->  {'UP' if fe_up else 'DOWN -- run start.py'}")
print(f"  config.js API_BASE = http://localhost:{backend_port}")
if fe_up:
    print(f"\n  ACTION: Open http://127.0.0.1:3000/index.html")
    print(f"          Then HARD REFRESH: Ctrl + Shift + R")
else:
    print(f"\n  ACTION: Run 'python start.py' first, then access http://127.0.0.1:3000/index.html")
print(f"{'='*60}\n")
