// Auto-generated by start.py — do NOT edit manually or commit to git
// Regenerated on every launch with the correct backend port
window.API_BASE = "http://localhost:9001"; // global — accessible to all scripts
